opsman-configuration:
  aws:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: ((region))
    vm_name: ((vm_name))
    vpc_subnet_id: ((vpc_subnet_id))
    security_group_id: ((security_group_id))
    key_pair_name: ((key_pair_name))
    iam_instance_profile_name: ((iam_instance_profile_name))
    instance_type:  ((instance_type))
    # At least one IP address (public or private) needs to be assigned to the VM.
    public_ip: ((public_ip))
    private_ip: ((private_ip))