product-name: pivotal-container-service
product-properties:
  .cloud_controller.system_domain:
    value: {{ (ds "data").sys_domain }}
  .cloud_controller.apps_domain:
    value: {{ (ds "data").apps_domain }}
  .ha_proxy.skip_cert_verify:
    value: true
  .properties.haproxy_forward_tls:
    value: disable
  .properties.tcp_routing:
    value: enable
  .properties.tcp_routing.enable.reservable_ports:
    value: 1024-1033
  .properties.security_acknowledgement:
    value: X
  .mysql_monitor.recipient_email:
    value: nobody@localhost
  .properties.credhub_internal_provider_keys:
    value:
    - name: default
      primary: true
      key:
        secret: askdnasoidansfiopanskflasf
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: "{{ (ds "data").tls_cert}}\n{{ (ds "data").tls_cert_ca}}"
        private_key_pem: "{{ (ds "data").tls_cert_key}}"
      name: default
  .uaa.service_provider_key_credentials:
    value:
        cert_pem: "{{ (ds "data").tls_cert}}\n{{ (ds "data").tls_cert_ca}}"
        private_key_pem: "{{ (ds "data").tls_cert_key}}"
network-properties:
  network:
    name: pas
  other_availability_zones:
    {{range (ds "data").azs}}
    - name: {{.}}
    {{end}}
  singleton_availability_zone:
    name: {{index (ds "data").azs 0}}
resource-config:
  control:
    elb_names:
    {{range (ds "data").ssh_target_groups}}
    - alb:{{.}}
    {{end}}
    additional_vm_extensions: [ssh_lb_security_groups]
  router:
    elb_names:
    {{range (ds "data").web_target_groups}}
    - alb:{{.}}
    {{end}}
    additional_vm_extensions: [web_lb_security_groups]
  tcp_router:
    elb_names:
    {{range (ds "data").tcp_target_groups}}
    - alb:{{.}}
    {{end}}
    additional_vm_extensions: [tcp_lb_security_groups]
  compute:
    instances: 1
  blobstore:
    instances: 1
  mysql_monitor:
    instances: 1
