---
product-name: pivotal-container-service
network-properties:
  network:
    name: {{.pks_subnet_name}}
  service_network:
    name: {{.services_subnet_name}}
  other_availability_zones:
    - name: 'zone-2'
  singleton_availability_zone:
    name: 'zone-1'
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: |
{{indent 10 .ssl_cert}}
      private_key_pem: |
{{indent 10 .ssl_private_key}}
  .properties.plan1_selector.active.master_az_placement:
    value:
    - 'zone-1'
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - 'zone-1'
    - 'zone-2'
  .properties.plan2_selector:
    value: "Plan Inactive"
  .properties.plan3_selector:
    value: "Plan Inactive"
  .properties.pks_api_hostname:
    value: {{.pks_api_hostname}}
  .properties.cloud_provider:
    value: Azure
  .properties.cloud_provider.azure.subscription_id:
    value: {{.subscription_id}}
  .properties.cloud_provider.azure.tenant_id:
    value: {{.tenant_id}}
  .properties.cloud_provider.azure.location:
    value: {{.location}}
  .properties.cloud_provider.azure.resource_group_name:
    value: {{.pcf_resource_group_name}}
  .properties.cloud_provider.azure.vnet_resource_group_name:
    value: {{.pcf_resource_group_name}}
  .properties.cloud_provider.azure.vnet_name:
    value: {{.network_name}}
  .properties.cloud_provider.azure.default_security_group:
    value: {{.bosh_deployed_vms_security_group_name}}
  .properties.cloud_provider.azure.primary_availability_set:
    value: {{.azurerm_availability_set_name}}
  .properties.cloud_provider.azure.azure_master_managed_identity:
    value: {{.master_managed_identity}}
  .properties.cloud_provider.azure.azure_worker_managed_identity:
    value: {{.worker_managed_identity}}
  .properties.oidc_selector:
    value: disabled
  .properties.telemetry_selector:
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    value: not_provided
resource-config:
  pivotal-container-service:
    elb_names:
    - {{.pks_lb_name}}
errand-config:
  smoke-tests:
    post-deploy-state: true
